### PR TITLE
Raw mode

### PR DESCRIPTION
**Pull request by m4rkw**
Hello again,
- added SEND_RAW mode to send the data packet over a raw TCP connection in order to minimise bandwidth
- added example daemon.rb ruby tcp server to accept and log the raw data packets
- added boolean flags for all elements in the data packet so they can be turned on and off individually

Raw mode drastically reduces the bandwidth used by the OpenTracker.

Example old data transmission using HTTP:

POST /index.php HTTP/1.0\r\nHost: some.server.com \r\nContent-type: application/x-www-form-urlencoded\r\nContent-length: 42\r\nConnection: close\r\n\r\nimei=8634241016201447&key=xxxxxxxxx&d=15/05/10,09:40:40 0[100515,9404700,12.394991,-4.132110,0.02,18.70,346.90,67,15]12.24,0,2520#eof

New data packet using raw mode and only a few select data items:

xxxxxxxxx,12.345968,-1.234517,0.04,12.42,0,2880

273 bytes down to 47 bytes.

For users sending 1440 requests/day like I do, that drops the monthly bandwidth from 11.25MB down to just 1.94MB.

Mark

### CODE REVIEW

**Comment by m4rkw** [comment]
Closed as this doesn't actually work in practice - carriers round the individual data packets up to whatever their billing increment is, which is always >= 1kb.  I will investigate whether it can be made to work by keeping the tcp connection open but that's a problem for another day.

**Comment by opensourcegps** [comment]
if you want to save traffic and do not care much of real time sending, it might be easier to just send packets once per 5 (configurable) data collections. So you collect your data, store it in memory, repeat 5 times and then send combined data. 

I think this was planned with INTERVAL_SEND but never properly implemented.

**Comment by m4rkw** [comment]
Yeah, I do kind of want real-time sending because it's useful for me.  I think it should be possible to stretch the sessions out by keeping the tcp connections alive and reusing them, or another idea which has been suggested to me is to use DNS and send it via the carriers own dns servers with your subdomain, eg:

<lat>.<lon>.<speed>.<timestamp>.mydomain.com

The <timestamp> would ensure all requests are unique and so their dns servers would forward the requests to me.  Apparently several GSM networks don't include DNS traffic in their data billing ;)

**Comment by m4rkw** [comment]
oh my comment got stripped, i meant:

(lat).(lon).(speed).(timestamp).mydomain.com

where (timestamp) ensures every lookup is unique

**Pull request closed without merging**
